using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace WorldNet.SourceGenerator;

[Generator]
public sealed class ScratchLayoutGenerator : IIncrementalGenerator
{
    private const string AttributeName = "WorldNet.ScratchLayoutAttribute";

    private const string AttributeSource = """
        namespace WorldNet;

        [System.AttributeUsage(System.AttributeTargets.Struct)]
        internal sealed class ScratchLayoutAttribute : System.Attribute
        {
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx => ctx.AddSource(
            "ScratchLayoutAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        IncrementalValuesProvider<ScratchModel?> models = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeName,
                static (node, _) => true,
                static (ctx, _) => Describe((INamedTypeSymbol)ctx.TargetSymbol));

        context.RegisterSourceOutput(models, static (ctx, model) =>
        {
            if (model is null)
            {
                return;
            }
            ctx.AddSource($"{model.TypeName}.Scratch.g.cs",
                SourceText.From(Render(model), Encoding.UTF8));
        });
    }

    private static ScratchModel? Describe(INamedTypeSymbol type)
    {
        IMethodSymbol? layout = type.GetMembers("Layout")
            .OfType<IMethodSymbol>()
            .FirstOrDefault(m => m.IsStatic
                && m.TypeParameters.Length == 1
                && m.Parameters.Length >= 2
                && m.Parameters[0].RefKind == RefKind.Ref
                && m.Parameters[m.Parameters.Length - 1].RefKind == RefKind.Ref
                && SymbolEqualityComparer.Default.Equals(
                    m.Parameters[m.Parameters.Length - 1].Type, type));

        if (layout is null)
        {
            return null;
        }

        ImmutableArray<Parameter>.Builder dimensions = ImmutableArray.CreateBuilder<Parameter>();
        for (int i = 1; i < layout.Parameters.Length - 1; ++i)
        {
            IParameterSymbol parameter = layout.Parameters[i];
            dimensions.Add(new Parameter(
                parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                parameter.Name));
        }

        bool hasMeasure = type.GetMembers("GetRequiredArenaBytes").OfType<IMethodSymbol>().Any();
        bool hasBind = type.GetMembers("Bind").OfType<IMethodSymbol>().Any();

        return new ScratchModel(
            type.ContainingNamespace.ToDisplayString(),
            type.Name,
            dimensions.ToImmutable(),
            hasMeasure,
            hasBind);
    }

    private static string Render(ScratchModel model)
    {
        string parameterList = string.Join(", ",
            model.Dimensions.Select(static d => $"{d.Type} {d.Name}"));
        string argumentList = string.Join(", ", model.Dimensions.Select(static d => d.Name));
        string separator = model.Dimensions.Length == 0 ? string.Empty : ", ";

        StringBuilder builder = new();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine($"namespace {model.Namespace};");
        builder.AppendLine();
        builder.AppendLine($"unsafe partial struct {model.TypeName}");
        builder.AppendLine("{");

        if (!model.HasMeasure)
        {
            builder.AppendLine(
                $"    public static nuint GetRequiredArenaBytes({parameterList})");
            builder.AppendLine("    {");
            builder.AppendLine("        global::WorldNet.MeasuringAllocator allocator = default;");
            builder.AppendLine($"        {model.TypeName} scratch = default;");
            builder.AppendLine(
                $"        Layout(ref allocator{separator}{argumentList}, ref scratch);");
            builder.AppendLine("        return allocator.Total;");
            builder.AppendLine("    }");
        }

        if (!model.HasBind)
        {
            if (!model.HasMeasure)
            {
                builder.AppendLine();
            }
            builder.AppendLine(
                $"    public static {model.TypeName} Bind(global::WorldNet.WorldArena arena{separator}{parameterList})");
            builder.AppendLine("    {");
            builder.AppendLine(
                "        global::WorldNet.ArenaAllocator allocator = new(arena);");
            builder.AppendLine($"        {model.TypeName} scratch = default;");
            builder.AppendLine(
                $"        Layout(ref allocator{separator}{argumentList}, ref scratch);");
            builder.AppendLine("        return scratch;");
            builder.AppendLine("    }");
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private sealed record Parameter(string Type, string Name);

    private sealed record ScratchModel(
        string Namespace,
        string TypeName,
        ImmutableArray<Parameter> Dimensions,
        bool HasMeasure,
        bool HasBind);
}
